### ISSUE TITLE
Possible typo in BBC Micro source in this repo

### ISSUE THREAD

**Issue by ahope1** [bchiha/dungeon-of-doom#2]
While converting the game for the MC-10 computer, Jim Gerrie [noticed](https://jimgerrie.blogspot.com/2022/12/usborne-books-dungeon-of-doom-1984.html) a possible typo on [line 950](https://github.com/bchiha/dungeon-of-doom/blob/691f37c4b531a31b318ad7d9a4308f9d57b762f5/bbc/game_module.bas#L103) of the game module: the ".5" should actually be ".1" as in the original listing in the printed book (and the PDF).

Do you agree with Jim's "bug report"? Or did you deliberately change the ".1" to a ".5" for some reason?

**Comment by bchiha** [comment]
Hey. Firstly thanks for checking out my code!  I'll check it out later today. I might have tweaked it slightly to make it play better. I'll get back to you.

**Comment by ahope1** [comment]
Thanks! 

Btw, I don’t know if you remember but we have spoken before: https://github.com/bchiha/dungeon-of-doom/issues/1

**Comment by bchiha** [comment]
I remember you.  Besides my Mother, you seem to be my only fan!   lol..

I have to get in contact with Jim, That write up is really well done!.  Okay, Yes, I did change this from 0.1 to 0.5.  The reason was that, if the MAP doesn't have enough Enemies or ways to build experience, it blocks you from descending the dungeon.  IE: you need experience > 1 to get to Level 2.  If it only updates with 0.1 for every kill, you will get stuck.  

For clarity and correctness, I'll fix this.  But I think the version on the BBC page that you loaded (my claim to fame!) will have the 0.5 in the code as the levels that I created are small...

Cheers, Brian

**Comment by ahope1** [comment]
Thanks for the reply! Yes, I am definitely a fan! 😂

It sounds like there was a good reason for you to change the value to 0.5. I think you’re saying that the dungeons on the disc-image that I uploaded to the Complete BBC Micro Games Archive at [bbcmicro.co.uk](http://bbcmicro.co.uk/game.php?id=3073) actually *require* a value of 0.5, so I guess I *won’t* change my copy of the program at the CBMGArchive then?

**Comment by bchiha** [comment]
I've fixed the code to match the original source.  Looking at the example levels that Jim has done, his level has more monsters, so racking up experience points is much steeper.  Thanks again for putting the code on the bbcmicro site.  I often show other keen retro friends the link!
